apiVersion: v1
kind: Service
metadata:
  name: cribl-stream-ui
  namespace: monitoring
  labels:
    app: cribl-stream
spec:
  type: NodePort
  selector:
    app: cribl-stream
  ports:
    - name: ui
      port: 9000
      targetPort: 9000
      nodePort: 30900
      protocol: TCP
